// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelesEducacao.Pagamentos.Data;

#nullable disable

namespace TelesEducacao.Pagamentos.Data.Migrations
{
    [DbContext(typeof(PagamentosContext))]
    [Migration("20260208202046_AjustePagamentos")]
    partial class AjustePagamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TelesEducacao.Pagamentos.Business.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("TelesEducacao.Pagamentos.Business.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusTransacao")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoId")
                        .IsUnique();

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("TelesEducacao.Pagamentos.Business.Pagamento", b =>
                {
                    b.OwnsOne("TelesEducacao.Pagamentos.Business.DadosCartao", "DadosCartao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Cvv")
                                .IsRequired()
                                .HasColumnType("varchar(4)")
                                .HasColumnName("CvvCartao");

                            b1.Property<string>("Expiracao")
                                .IsRequired()
                                .HasColumnType("varchar(10)")
                                .HasColumnName("ExpiracaoCartao");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("varchar(250)")
                                .HasColumnName("NomeCartao");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("varchar(16)")
                                .HasColumnName("NumeroCartao");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.Navigation("DadosCartao")
                        .IsRequired();
                });

            modelBuilder.Entity("TelesEducacao.Pagamentos.Business.Transacao", b =>
                {
                    b.HasOne("TelesEducacao.Pagamentos.Business.Pagamento", "Pagamento")
                        .WithOne("Transacao")
                        .HasForeignKey("TelesEducacao.Pagamentos.Business.Transacao", "PagamentoId")
                        .IsRequired();

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("TelesEducacao.Pagamentos.Business.Pagamento", b =>
                {
                    b.Navigation("Transacao")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
